name: kingdom_of_aldoria
description: Epic 2D Mobile RPG Adventure - Flutter Edition
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Game Engine
  flame: ^1.10.1
  flame_audio: ^2.0.4
  
  # UI & Animations
  flutter_animate: ^4.2.0
  lottie: ^2.7.0
  animated_text_kit: ^4.2.2
  
  # State Management
  provider: ^6.1.1
  riverpod: ^2.4.9
  flutter_riverpod: ^2.4.9
  
  # Storage & Data
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Device Features
  vibration: ^1.8.4
  wakelock: ^0.6.2
  device_info_plus: ^9.1.1
  package_info_plus: ^4.2.0
  
  # Audio & Haptics
  audioplayers: ^5.2.1
  flutter_vibrate: ^1.3.0
  haptic_feedback: ^0.5.0
  
  # UI Enhancements
  google_fonts: ^6.1.0
  flutter_screenutil: ^5.9.0
  auto_size_text: ^3.0.0
  
  # Navigation
  go_router: ^12.1.3
  
  # Networking (future updates)
  dio: ^5.3.3
  connectivity_plus: ^5.0.2
  
  # Utils
  logger: ^2.0.2+1
  uuid: ^4.2.1
  
  # Icons & Assets
  cupertino_icons: ^1.0.6
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

# App Icons
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icons/app_icon.png"
    background_color: "#1a1a2e"
    theme_color: "#FFD700"
  windows:
    generate: true
    image_path: "assets/icons/app_icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/icons/app_icon.png"

# Splash Screen
flutter_native_splash:
  color: "#1a1a2e"
  image: assets/images/splash_logo.png
  color_dark: "#0f3460"
  image_dark: assets/images/splash_logo.png
  android_12:
    image: assets/images/splash_logo.png
    color: "#1a1a2e"
  ios: true
  web: true

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/images/
    - assets/icons/
    - assets/audio/music/
    - assets/audio/sounds/
    - assets/animations/
    - assets/data/

  # Fonts
  fonts:
    - family: GameFont
      fonts:
        - asset: assets/fonts/GameFont-Regular.ttf
        - asset: assets/fonts/GameFont-Bold.ttf
          weight: 700